name: CI
on:
    pull_request:
        branches: [main]

jobs:
    tests:
        runs-on: ubuntu-latest
        env:
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
            ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
            PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
            PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - run: npm ci
            - run: npx hardhat test
